export const TARGETED = 'ACTIONS_TARGETED';
export const SELF_TARGETED = 'ACTIONS_SELF_TARGETED';
export const DOUBLE_TARGETED = 'ACTIONS_DOUBLE_TARGETED';
export const ALLY_TARGETED = 'ACTIONS_ALLY_TARGETED';
